In [1]:
from scipy.special import sph_harm
from scipy.integrate import dblquad
from numpy import pi, conj, sqrt, sin, cos

In [2]:
print(sph_harm(1,2,0,1))
print(conj(sph_harm(1,2,0,1)))

(-0.3512381379488298+0j)
(-0.3512381379488298-0j)


In [3]:
def s11(theta,phi): return sph_harm(1,1,theta,phi)
def f(theta,phi): return s11(theta,phi)*conj(s11(theta,phi))

In [4]:
dblquad(f,0,2*pi,0,pi)

/home/qd4314/.local/lib/python3.7/site-packages/scipy/integrate/quadpack.py:448: ComplexWarning: Casting complex values to real discards the imaginary part
  return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)


(1.1780972450961729, 8.647045785402527e-10)

In [5]:
def s12(theta,phi): return sph_harm(1,2,theta,phi)
def g(theta,phi): return s11(theta,phi)*(s12(theta,phi))

In [6]:
dblquad(g,0,2*pi,0,pi)

(2.8177095519581625e-18, 2.2906578031139133e-15)

In [7]:
def sph(theta,phi): return sph_harm(4,5,theta,phi)
def h(theta,phi): return sph(phi,theta)*conj(sph(phi,theta))*sin(theta)

In [8]:
dblquad(h,0,2*pi,0,pi)

(0.9999999999999999, 2.7106618893935064e-09)

In [9]:
from numpy import array
from numpy import append, stack

In [10]:
a =[1.0,2,3]

In [11]:
b= [4.0,5,6]

In [12]:
append(a,b)

array([1., 2., 3., 4., 5., 6.])

In [13]:
stack([a,b],axis=1)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [17]:
from numpy.random import rand, randn
from numpy.linalg import norm

In [19]:

a = rand(10,3)

In [22]:
norm(a,axis=1)-1.0

array([-0.00342734,  0.19984604,  0.25103467, -0.62343395,  0.18890294,
       -0.2029284 , -0.01370972, -0.21900307,  0.16637406, -0.07414254])

In [23]:
a = rand(3)
b = rand(3)
a-b

array([ 0.44121142,  0.77101676, -0.61727111])

In [24]:
shape(a)

NameError: name 'shape' is not defined

In [25]:
a.shape

(3,)

In [26]:
len(a.shape)

1

In [27]:
a = rand(3,3)
b = rand(10,3)

In [28]:
a

array([[0.15778819, 0.54087519, 0.39490851],
       [0.46230121, 0.12266306, 0.84940615],
       [0.9249512 , 0.49543394, 0.22693866]])

In [29]:
b

array([[0.06962781, 0.75369998, 0.73453105],
       [0.05891905, 0.61828941, 0.45122709],
       [0.06917219, 0.02556418, 0.09845482],
       [0.75512491, 0.82885933, 0.8483488 ],
       [0.24015994, 0.82922205, 0.63496324],
       [0.03480201, 0.4099208 , 0.69105379],
       [0.74755636, 0.78261876, 0.67362314],
       [0.6772647 , 0.21705955, 0.27477512],
       [0.5346192 , 0.58072186, 0.14052353],
       [0.74009438, 0.96502664, 0.6476934 ]])

In [34]:
from numpy import matmul

In [36]:
matmul(a,b.T).T

array([[0.70871663, 0.74855536, 0.60450437],
       [0.52190755, 0.48635468, 0.46321967],
       [0.06362223, 0.1187423 , 0.09898947],
       [0.9024794 , 1.17135827, 1.30162187],
       [0.73715243, 0.75208283, 0.77705868],
       [0.50011036, 0.65335649, 0.39210566],
       [0.80727415, 1.01377426, 1.23206018],
       [0.33277753, 0.57312116, 0.79633256],
       [0.45394858, 0.43774978, 0.81409621],
       [0.89451676, 1.0106744 , 1.30964481]])